[package]
name = "vpinball-plugin-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "vpinball_plugin_rust"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]

[build-dependencies]
bindgen = "0.69.4"
